ExtraGog/src/java/jsf/clases/PublicadoresController.java
package jsf.clases;

import tablasBD.Publicadores;
import jsf.clases.util.JsfUtil;
import jsf.clases.util.PaginationHelper;
import beans.sessions.PublicadoresFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("publicadoresController")
@SessionScoped
public class PublicadoresController implements Serializable {

    private Publicadores current;
    private DataModel items = null;
    @EJB
    private beans.sessions.PublicadoresFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PublicadoresController() {
    }

    public Publicadores getSelected() {
        if (current == null) {
            current = new Publicadores();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PublicadoresFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Publicadores) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Publicadores();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PublicadoresCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Publicadores) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PublicadoresUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Publicadores) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PublicadoresDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Publicadores getPublicadores(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Publicadores.class)
    public static class PublicadoresControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PublicadoresController controller = (PublicadoresController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "publicadoresController");
            return controller.getPublicadores(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Publicadores) {
                Publicadores o = (Publicadores) object;
                return getStringKey(o.getIdPublicador());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Publicadores.class.getName());
            }
        }

    }

}

ExtraGog/web/pages/publicadores/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatePublicadoresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePublicadoresLabel_idPublicador}" for="idPublicador" />
                    <h:inputText id="idPublicador" value="#{publicadoresController.selected.idPublicador}" title="#{bundle.CreatePublicadoresTitle_idPublicador}" required="true" requiredMessage="#{bundle.CreatePublicadoresRequiredMessage_idPublicador}"/>
                    <h:outputLabel value="#{bundle.CreatePublicadoresLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{publicadoresController.selected.nombre}" title="#{bundle.CreatePublicadoresTitle_nombre}" required="true" requiredMessage="#{bundle.CreatePublicadoresRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.CreatePublicadoresLabel_idDesarrolladora}" for="idDesarrolladora" />
                    <h:inputText id="idDesarrolladora" value="#{publicadoresController.selected.idDesarrolladora}" title="#{bundle.CreatePublicadoresTitle_idDesarrolladora}" required="true" requiredMessage="#{bundle.CreatePublicadoresRequiredMessage_idDesarrolladora}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{publicadoresController.create}" value="#{bundle.CreatePublicadoresSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{publicadoresController.prepareList}" value="#{bundle.CreatePublicadoresShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreatePublicadoresIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

ExtraGog/web/pages/publicadores/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPublicadoresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPublicadoresLabel_idPublicador}" for="idPublicador" />
                    <h:inputText id="idPublicador" value="#{publicadoresController.selected.idPublicador}" title="#{bundle.EditPublicadoresTitle_idPublicador}" required="true" requiredMessage="#{bundle.EditPublicadoresRequiredMessage_idPublicador}"/>
                    <h:outputLabel value="#{bundle.EditPublicadoresLabel_nombre}" for="nombre" />
                    <h:inputText id="nombre" value="#{publicadoresController.selected.nombre}" title="#{bundle.EditPublicadoresTitle_nombre}" required="true" requiredMessage="#{bundle.EditPublicadoresRequiredMessage_nombre}"/>
                    <h:outputLabel value="#{bundle.EditPublicadoresLabel_idDesarrolladora}" for="idDesarrolladora" />
                    <h:inputText id="idDesarrolladora" value="#{publicadoresController.selected.idDesarrolladora}" title="#{bundle.EditPublicadoresTitle_idDesarrolladora}" required="true" requiredMessage="#{bundle.EditPublicadoresRequiredMessage_idDesarrolladora}"/>
                </h:panelGrid>
                <h:commandLink action="#{publicadoresController.update}" value="#{bundle.EditPublicadoresSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditPublicadoresViewLink}"/>
                <br />
                <h:commandLink action="#{publicadoresController.prepareList}" value="#{bundle.EditPublicadoresShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditPublicadoresIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

ExtraGog/web/pages/publicadores/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListPublicadoresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPublicadoresEmpty}" rendered="#{publicadoresController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{publicadoresController.items.rowCount > 0}">
                    <h:outputText value="#{publicadoresController.pagination.pageFirstItem + 1}..#{publicadoresController.pagination.pageLastItem + 1}/#{publicadoresController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{publicadoresController.previous}" value="#{bundle.Previous} #{publicadoresController.pagination.pageSize}" rendered="#{publicadoresController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{publicadoresController.next}" value="#{bundle.Next} #{publicadoresController.pagination.pageSize}" rendered="#{publicadoresController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{publicadoresController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicadoresTitle_idPublicador}"/>
                            </f:facet>
                            <h:outputText value="#{item.idPublicador}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicadoresTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicadoresTitle_idDesarrolladora}"/>
                            </f:facet>
                            <h:outputText value="#{item.idDesarrolladora}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{publicadoresController.prepareView}" value="#{bundle.ListPublicadoresViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{publicadoresController.prepareEdit}" value="#{bundle.ListPublicadoresEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{publicadoresController.destroy}" value="#{bundle.ListPublicadoresDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{publicadoresController.prepareCreate}" value="#{bundle.ListPublicadoresCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListPublicadoresIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

ExtraGog/web/pages/publicadores/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewPublicadoresTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewPublicadoresLabel_idPublicador}"/>
                    <h:outputText value="#{publicadoresController.selected.idPublicador}" title="#{bundle.ViewPublicadoresTitle_idPublicador}"/>
                    <h:outputText value="#{bundle.ViewPublicadoresLabel_nombre}"/>
                    <h:outputText value="#{publicadoresController.selected.nombre}" title="#{bundle.ViewPublicadoresTitle_nombre}"/>
                    <h:outputText value="#{bundle.ViewPublicadoresLabel_idDesarrolladora}"/>
                    <h:outputText value="#{publicadoresController.selected.idDesarrolladora}" title="#{bundle.ViewPublicadoresTitle_idDesarrolladora}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{publicadoresController.destroyAndView}" value="#{bundle.ViewPublicadoresDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewPublicadoresEditLink}"/>
                <br />
                <h:commandLink action="#{publicadoresController.prepareCreate}" value="#{bundle.ViewPublicadoresCreateLink}" />
                <br />
                <h:commandLink action="#{publicadoresController.prepareList}" value="#{bundle.ViewPublicadoresShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewPublicadoresIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>